name: Build
on: [ push ]
jobs:
  Test:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker Build
        run: |
          docker build -t autonomouslogic/semantic-release .

      - name: Version
        run: |
          docker run autonomouslogic/semantic-release --version

      - name: Test Release
        run: |
          git config --global user.email "test@example.com"
          git config --global user.name "test"
          pwd
          git status
          docker run -v $(pwd):/usr/src/app -e GITHUB_TOKEN=$GITHUB_TOKEN autonomouslogic/semantic-release --dry-run --branches $(git rev-parse --abbrev-ref HEAD)
